source 'https://github.com/SourceChang/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_modular_headers!

target 'MapWrapperFrameworkSwift_Example' do
  pod 'MapWrapperFrameworkSwift', :path => '../'

  target 'MapWrapperFrameworkSwift_Tests' do
    inherit! :search_paths

    
  end
end
